# Generated by Django 4.1.5 on 2023-02-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
