# Generated by Django 4.1.5 on 2023-02-05 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_ride_request_status_alter_ride_request_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=150)),
                ('arrival_time', models.DateTimeField()),
                ('numberOfPassenger', models.IntegerField(default=4)),
                ('canShare', models.BooleanField()),
                ('status', models.CharField(choices=[('open', 'open'), ('confirmed', 'confirmed'), ('completed', 'completed')], default='open', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Ride_request',
        ),
    ]
