# Generated by Django 4.1.5 on 2023-02-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_ride_delete_ride_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='owner',
        ),
    ]
