<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-02-05 19:52
=======
# Generated by Django 4.1.5 on 2023-02-05 19:53
>>>>>>> 766dd1b229f0f6d0cb36ec44a0ce82c623da02da

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile'),
        ('home', '0007_remove_ride_owner'),
    ]

    operations = [
    ]
