# Generated by Django 4.1.5 on 2023-02-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile'),
        ('home', '0007_remove_ride_owner'),
    ]

    operations = [
    ]
