# Generated by Django 4.1.5 on 2023-02-06 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_ride_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer_list',
            field=models.ManyToManyField(blank=True, related_name='sharer_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
