# Generated by Django 4.1.5 on 2023-02-07 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_ride_driver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='DriverStatus',
        ),
    ]
