# Generated by Django 4.1.5 on 2023-02-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_userprofile_driverstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('confirmed', 'confirmed'), ('open', 'open')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
