# Generated by Django 4.1.5 on 2023-02-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_ride_destination_alter_ride_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='destination',
        ),
        migrations.AddField(
            model_name='ride',
            name='dest',
            field=models.CharField(default='home', max_length=50),
        ),
    ]
