# Generated by Django 4.1.5 on 2023-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_ride_destination_ride_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dest',
            field=models.CharField(max_length=50),
        ),
    ]
