# Generated by Django 4.1.5 on 2023-02-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_ride_dest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='arrival_time',
            new_name='time_arrive',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='comment',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('confirmed', 'confirmed'), ('open', 'open')], default='open', max_length=50),
        ),
    ]
